var files =
[
    [ "extern", "dir_dc9e1e299a0b26f222fe6c0a872463f0.html", "dir_dc9e1e299a0b26f222fe6c0a872463f0" ],
    [ "include", "dir_d44c64559bbebec7f509842c48db8b23.html", "dir_d44c64559bbebec7f509842c48db8b23" ],
    [ "BlockStructure.cpp", "BlockStructure_8cpp.html", "BlockStructure_8cpp" ],
    [ "BoundaryPoint.cpp", "BoundaryPoint_8cpp.html", "BoundaryPoint_8cpp" ],
    [ "Container.cpp", "Container_8cpp.html", "Container_8cpp" ],
    [ "doci.cpp", "doci_8cpp.html", "doci_8cpp" ],
    [ "doci2.cpp", "doci2_8cpp.html", "doci2_8cpp" ],
    [ "doci_bp.cpp", "doci__bp_8cpp.html", "doci__bp_8cpp" ],
    [ "doci_bp2.cpp", "doci__bp2_8cpp.html", "doci__bp2_8cpp" ],
    [ "doci_sdp.cpp", "doci__sdp_8cpp.html", "doci__sdp_8cpp" ],
    [ "DPM.cpp", "DPM_8cpp.html", null ],
    [ "EIG.cpp", "EIG_8cpp.html", null ],
    [ "gen-hubbard.cpp", "gen-hubbard_8cpp.html", "gen-hubbard_8cpp" ],
    [ "gen-pairing.cpp", "gen-pairing_8cpp.html", "gen-pairing_8cpp" ],
    [ "helpers.cpp", "helpers_8cpp.html", "helpers_8cpp" ],
    [ "Lineq.cpp", "Lineq_8cpp.html", "Lineq_8cpp" ],
    [ "LocalMinimizer.cpp", "LocalMinimizer_8cpp.html", "LocalMinimizer_8cpp" ],
    [ "Matrix.cpp", "Matrix_8cpp.html", "Matrix_8cpp" ],
    [ "PHM.cpp", "PHM_8cpp.html", "PHM_8cpp" ],
    [ "PotentialReduction.cpp", "PotentialReduction_8cpp.html", null ],
    [ "PPHM.cpp", "PPHM_8cpp.html", null ],
    [ "print.cpp", "print_8cpp.html", "print_8cpp" ],
    [ "read_patrick.cpp", "read__patrick_8cpp.html", "read__patrick_8cpp" ],
    [ "scan_function.cpp", "scan__function_8cpp.html", "scan__function_8cpp" ],
    [ "SimulatedAnnealing.cpp", "SimulatedAnnealing_8cpp.html", null ],
    [ "SPM.cpp", "SPM_8cpp.html", "SPM_8cpp" ],
    [ "SUP.cpp", "SUP_8cpp.html", "SUP_8cpp" ],
    [ "Tools.cpp", "Tools_8cpp.html", null ],
    [ "TPM.cpp", "TPM_8cpp.html", "TPM_8cpp" ],
    [ "UniMatrix.cpp", "UniMatrix_8cpp.html", null ],
    [ "Vector.cpp", "Vector_8cpp.html", "Vector_8cpp" ]
];